name: Check Format

on: 
   push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check_format:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        elixir: [1.15],
        otp: [26]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1 
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - uses: 
        id: mix-format-cache
        with:
          path: deps
          key: ${{runner.os}}